--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_networking-chat-2ecc0ead-a4ef5fb2"]["networking-chat"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package