--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_networking-chat-afedab05-212d8f64"]["networking-chat"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package