--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["rodux-networking-21fab336-3c77c96c"]["rodux-networking"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package