--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["rodux-networking-9e6dfa4f-e93009c1"]["rodux-networking"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package