[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"
proxy = "https://github.com/roblox/rotriever-proxy-index"

[dependencies]
Roact = "github.com/roblox/roact@1.3.1"
Rodux = "github.com/roblox/rodux@1.0"
RoactRodux = "github.com/roblox/roact-rodux@0.2"
RoactNavigation = "github.com/roblox/roact-navigation@0.4.1"
Cryo = "github.com/roblox/cryo@1.0"
Dash = "github.com/roblox/dash@0.1"
LuaChatDeps = { git = "https://github.com/Roblox/lua-chat-deps" }
LuaDiscussionsDeps = { git = "https://github.com/Roblox/lua-discussions-deps" }
LuaSocialLibrariesDeps = { git = "https://github.com/Roblox/lua-social-libraries-deps" }
PremiumUpsellDeps = { git = "https://github.com/Roblox/premium-upsell-deps" }
AvatarExperienceDeps = { git = "https://github.com/Roblox/avatar-experience-deps" }
PurchasePromptDeps = { git = "https://github.com/Roblox/purchase-prompt-deps" }
IAPExperience = { git = "https://github.com/Roblox/IAPExperience", rev = "master" }
UIBlox = { git = "https://github.com/Roblox/uiblox", rev = "master" }
Otter = "github.com/roblox/otter@0.1.3"
t = "github.com/roblox/t@1.0"
enumerate = "github.com/roblox/enumerate@1.0.0"
PolicyProvider = { git = "https://github.com/Roblox/lua-roact-policy-provider", rev = "master" }
Lumberyak = { git = "https://github.com/Roblox/lumberyak" }
StringUtilities = "github.com/Roblox/string-utilities@1.0.0"
UrlBuilder = "github.com/Roblox/url-builder@1.0.4"
FitFrame = "github.com/roblox/roact-fit-components@1.2.5"

# The following packages were ported from AppTempCommon
Promise = { git = "https://github.com/Roblox/lua-promise" }
Result = { git = "https://github.com/Roblox/lua-result" }
tutils = { git = "https://github.com/Roblox/tutils" }

InGameMenuDependencies = { git = "https://github.com/Roblox/in-game-menu-dependencies", rev = "master" }

RoactGamepad = "github.com/roblox/roact-gamepad@0.4.6"

[dev_dependencies]
TestEZ = "github.com/roblox/testez@0.4.0"
Rhodium = "github.com/roblox/rhodium@0.2.5"
DeveloperToolsOld = { git = "https://github.com/Roblox/developer-tools", rev = "90266d9" }
DeveloperTools = "github.com/Roblox/developer-tools@0.1.8"

# Patch all dependencies upon rodux to the flagged indireciton package, which
# will ensure that we always use only one rodux version
[patch."github.com/roblox/rodux"]
git = "https://github.com/roblox/rodux-flagged-upgrade"
rev = "1.1-to-3.0"

[patch."https://github.com/Roblox/lua-promise"]
git = "https://github.com/Roblox/roblox-lua-promise"
rev = "master"