--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["evaera_roblox-lua-promise"]["roblox-lua-promise"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package